<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Diwali 2024 Countdown</title>
    <style>
        /* Previous styles remain the same */
        body {
            margin: 0;
            min-height: 100vh;
            background: linear-gradient(45deg, #1a0f24, #2c1810);
            font-family: Arial, sans-serif;
            color: #fff;
            text-align: center;
            overflow: hidden;
        }

        .countdown-section {
            position: fixed;
            top: 20px;
            right: 20px;
            background: rgba(0, 0, 0, 0.7);
            padding: 20px;
            border-radius: 15px;
            border: 2px solid #ffd700;
            box-shadow: 0 0 20px rgba(255, 215, 0, 0.3);
            z-index: 100;
        }

        .countdown-title {
            color: #ffd700;
            font-size: 1.2em;
            margin-bottom: 10px;
            text-shadow: 0 0 5px rgba(255, 215, 0, 0.5);
        }

        .countdown {
            font-size: 1.8em;
            color: #fff;
            text-shadow: 0 0 10px rgba(255, 255, 255, 0.5);
        }

        .container {
            position: relative;
            padding: 20px;
            z-index: 1;
            max-width: 1000px;
            margin: 0 auto;
        }

        h1 {
            font-size: 3em;
            margin: 30px 0;
            color: #ffd700;
            text-shadow: 0 0 15px rgba(255, 215, 0, 0.7);
        }

        .quotes-container {
            margin: 30px auto;
            max-width: 800px;
            padding: 25px;
            background: rgba(0, 0, 0, 0.4);
            border-radius: 15px;
            border: 2px solid rgba(255, 215, 0, 0.4);
            box-shadow: 0 0 20px rgba(255, 215, 0, 0.2);
        }

        .quote {
            font-size: 1.3em;
            margin: 20px 0;
            color: #ffa500;
            text-shadow: 0 0 5px rgba(255, 165, 0, 0.4);
            line-height: 1.7;
            font-style: italic;
        }

        .celebrate-btn {
            padding: 20px 40px;
            font-size: 1.5em;
            background: linear-gradient(45deg, #ff4500, #ffd700);
            border: none;
            border-radius: 30px;
            color: white;
            cursor: pointer;
            transition: all 0.3s ease;
            margin-top: 30px;
            box-shadow: 0 0 20px rgba(255, 215, 0, 0.6);
            text-shadow: 0 0 10px rgba(255, 255, 255, 0.5);
            animation: pulse 2s infinite;
        }

        @keyframes pulse {
            0% { transform: scale(1); }
            50% { transform: scale(1.05); }
            100% { transform: scale(1); }
        }

        .celebrate-btn:hover {
            transform: scale(1.1);
            box-shadow: 0 0 30px rgba(255, 215, 0, 0.8);
        }

        .celebrate-btn:active {
            transform: scale(0.95);
        }

        .message {
            font-size: 1.8em;
            margin: 30px 0;
            color: #ffa500;
            line-height: 1.8;
        }

        .credits {
            position: fixed;
            bottom: 20px;
            width: 100%;
            text-align: center;
            color: #ffd700;
            font-size: 1.3em;
            text-shadow: 0 0 8px rgba(255, 215, 0, 0.6);
            z-index: 2;
            background: rgba(0, 0, 0, 0.3);
            padding: 10px 0;
        }

        .diya {
            font-size: 4em;
            margin: 20px 0;
            animation: flicker 1.5s infinite;
        }

        @keyframes flicker {
            0%, 100% { opacity: 1; text-shadow: 0 0 20px #ffa500; }
            50% { opacity: 0.8; text-shadow: 0 0 10px #ffa500; }
        }
    </style>
</head>
<body>
    <div class="countdown-section">
        <div class="countdown-title">Time Until Diwali</div>
        <div class="countdown" id="countdown"></div>
    </div>

    <div class="container">
        <div class="diya">🪔</div>
        <h1>Happy Diwali 2024</h1>
        <div class="message">
            Warm Diwali Wishes<br>
            From<br>
            <span style="color: #ffd700; font-size: 1.2em; text-shadow: 0 0 10px #ffd700;">Rajeev Mishra</span><br>
            To All Dear Friends
        </div>

        <div class="quotes-container">
            <div class="quote">"May the divine light of Diwali spread into your life peace, prosperity, happiness, and good health"</div>
            <div class="quote">"Let this Diwali burn all your bad times and enter you in good times"</div>
            <div class="quote">"May the joy of Diwali illuminate your life and fill your days with the bright sparkles of peace, mirth & goodwill"</div>
        </div>

        <button class="celebrate-btn" onclick="celebrate()">Celebrate Diwali! 🎆</button>
    </div>
    <div class="credits">Created by ANUJ MISHRA</div>

    <script>
        // Enhanced bomb blast sounds with higher intensity
        const bombSounds = [
            new Audio('data:audio/mp3;base64,SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU4Ljc2LjEwMAAAAAAAAAAAAAAA/+M4wAAAAAAAAAAAAEluZm8AAAAPAAAAEAAABVgANTU1NTU1Q0NDQ0NDUFBQUFBQXl5eXl5ea2tra2tra3l5eXl5eYaGhoaGhpSUlJSUlKGhoaGhoaGvr6+vr6+8vLy8vLzKysrKysrX19fX19fX5eXl5eXl8vLy8vLy////////////AAAAAExhdmM1OC4xMwAAAAAAAAAAAAAAACQCkAAAAAAAAAVY5qJZugAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+MYxAAAAANIAAAAAExBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxDsAAANIAAAAAFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV'),
            new Audio('data:audio/mp3;base64,SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU4Ljc2LjEwMAAAAAAAAAAAAAAA/+M4wAAAAAAAAAAAAEluZm8AAAAPAAAAEAAABVgANTU1NTU1Q0NDQ0NDUFBQUFBQXl5eXl5ea2tra2tra3l5eXl5eYaGhoaGhpSUlJSUlKGhoaGhoaGvr6+vr6+8vLy8vLzKysrKysrX19fX19fX5eXl5eXl8vLy8vLy////////////AAAAAExhdmM1OC4xMwAAAAAAAAAAAAAAACQCkAAAAAAAAAVY5qJZugAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+MYxAAAAANIAAAAAExBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxDsAAANIAAAAAFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV'),
            new Audio('data:audio/mp3;base64,SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU4Ljc2LjEwMAAAAAAAAAAAAAAA/+M4wAAAAAAAAAAAAEluZm8AAAAPAAAAEAAABVgANTU1NTU1Q0NDQ0NDUFBQUFBQXl5eXl5ea2tra2tra3l5eXl5eYaGhoaGhpSUlJSUlKGhoaGhoaGvr6+vr6+8vLy8vLzKysrKysrX19fX19fX5eXl5eXl8vLy8vLy////////////AAAAAExhdmM1OC4xMwAAAAAAAAAAAAAAACQCkAAAAAAAAAVY5qJZugAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+MYxAAAAANIAAAAAExBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxDsAAANIAAAAAFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV')
        ];

        // Extra loud launch sound
        const bombLaunchSound = new Audio('data:audio/mp3;base64,SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU4Ljc2LjEwMAAAAAAAAAAAAAAA/+M4wAAAAAAAAAAAAEluZm8AAAAPAAAAEAAABVgANTU1NTU1Q0NDQ0NDUFBQUFBQXl5eXl5ea2tra2tra3l5eXl5eYaGhoaGhpSUlJSUlKGhoaGhoaGvr6+vr6+8vLy8vLzKysrKysrX19fX19fX5eXl5eXl8vLy8vLy////////////AAAAAExhdmM1OC4xMwAAAAAAAAAAAAAAACQCkAAAAAAAAAVY5qJZugAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+MYxAAAAANIAAAAAExBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV/+MYxDsAAANIAAAAAFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV');

        // Countdown Timer
        function updateCountdown() {
            const targetDate = new Date('November 1, 2024 00:00:00').getTime();
            const now = new Date().getTime();
            const difference = targetDate - now;

            const days = Math.floor(difference / (1000 * 60 * 60 * 24));
            const hours = Math.floor((difference % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            const minutes = Math.floor((difference % (1000 * 60 * 60)) / (1000 * 60));
            const seconds = Math.floor((difference % (1000 * 60)) / 1000);

            document.getElementById('countdown').innerHTML = 
                `${days}d : ${hours}h : ${minutes}m : ${seconds}s`;
        }

        setInterval(updateCountdown, 1000);
        updateCountdown();

        // Enhanced Firework particle
        class Particle {
            constructor(x, y, color) {
                this.x = x;
                this.y = y;
                this.color = color;
                this.velocity = {
                    x: (Math.random() - 0.5) * 15, // Increased spread
                    y: Math.random() * -15
                };
                this.alpha = 1;
                this.friction = 0.98;
                this.gravity = 0.35;
                this.size = Math.random() * 4 + 2; // Larger particles
            }

            draw() {
                ctx.save();
                ctx.globalAlpha = this.alpha;
                ctx.fillStyle = this.color;
                ctx.beginPath();
                ctx.arc(this.x, this.y, this.size, 0, Math.PI * 2);
                ctx.fill();
                ctx.restore();
            }

            update() {
                this.velocity.x *= this.friction;
                this.velocity.y *= this.friction;
                this.velocity.y += this.gravity;
                this.x += this.velocity.x;
                this.y += this.velocity.y;
                this.alpha -= 0.006; // Slower fade
            }
        }

        // Canvas setup
        const canvas = document.createElement('canvas');
        canvas.style.position = 'fixed';
        canvas.style.top = '0';
        canvas.style.left = '0';
        canvas.style.width = '100%';
        canvas.style.height = '100%';
        canvas.style.pointerEvents = 'none';
        document.body.appendChild(canvas);
        
        const ctx = canvas.getContext('2d');
        canvas.width = window.innerWidth;
        canvas.height =
